name: Deploy Tutorials
on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'sparrowcode/Website'
    name: Deploy to site
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_ACTIONS_KEY }}
          script: bash update_articles.sh
